plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'Forge Transformers'
description = 'Forge-specific transformers unrelated to the FML project.'

dependencies {
    implementation(libs.bundles.asm ){ transitive = false } // Needed by all the black magic
    implementation(libs.log4j.api   ){ transitive = false }
    implementation(libs.gson        ){ transitive = false }
    implementation(libs.modlauncher ){ transitive = false }
    implementation(libs.coremods.api){ transitive = false }
}

convention.manifest('net/minecraftforge/forge/transformers/')
tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Automatic-Module-Name': 'net.minecraftforge.forge.transformers',
            'Forge-Module-Layer'   : 'boot'
        ])
    }
}

convention.publish()
