plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'LowCodeMod'
description = 'Language provider for Minecraft Forge that loads mods without a Java entrypoint.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
}

convention.langProvider('net/minecraftforge/fml/lowcodemod/')

convention.publish()