plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'JavaFMLMod'
description = 'Language provider for Minecraft Forge that provides basic Java mod functionality.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
    implementation libs.unsafe
    implementation libs.securemodules
}

convention.langProvider('net/minecraftforge/fml/javafmlmod/')

convention.publish()