plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'MCLanguage'
description = 'Language provider for Minecraft Forge that provides Minecraft Itself.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
}

convention.langProvider('net/minecraftforge/fml/mclanguageprovider/')

convention.publish()
