plugins {
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'FML'
description = 'Core library used for Forge ModLoader.'

dependencies {
    api libs.eventbus

    implementation projects.fmlloader
    implementation libs.commons.io
}

convention.manifest('net/minecraftforge/fml/')
tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Automatic-Module-Name': 'net.minecraftforge.fmlcore',
            'FMLModType'           : 'LIBRARY'
        ])
    }
}

convention.publish()
