import org.gradle.api.plugins.jvm.JvmTestSuite

plugins {
    id 'jvm-test-suite'
    id 'net.minecraftforge.forge.build.convention'
}

gradleutils.displayName = 'FML Early Display'
description = 'A pretty looking, but prone to erroring screen displayed during Forge loading.'

dependencies {
    implementation projects.fmlloader
    implementation projects.fmlcore
    implementation libs.bundles.lwjgl
    implementation earlyDisplayLibs.slf4j.api
    implementation libs.jopt.simple
}

testing.suites.named('test', JvmTestSuite) {
    useJUnitJupiter('5.8.2')

    dependencies {
        implementation earlyDisplayTestLibs.powermock.core
        runtimeOnly earlyDisplayLibs.slf4j.jdk14
        runtimeOnly.bundle convention.nativeVariants(earlyDisplayTestLibs.bundles.lwjgl)
    }
}

convention.manifest('net/minecraftforge/fml/earlydisplay/')
tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Automatic-Module-Name': 'net.minecraftforge.earlydisplay',
            'Forge-Module-Layer'   : 'boot'
        ])
    }
}

convention.publish()